language: php
sudo: false

php:
  - 5.4

addons:
  code_climate:
    repo_token: 4e46bba90af9f2a2e37ce22be162c47b329a646e258038ef937028e02f2a464b

before_script:
  - composer install --dev

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter
